name: Build and Deploy Maven Project

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: windows-2022 

    steps:
    # Step 1: Checkout the code from your repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Java 20 on the Windows environment
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '20' # Java 20

    # Step 3: Cache Maven dependencies
    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: C:\Users\runneradmin\.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build the Maven project and create the WAR file
    - name: Build with Maven
      run: mvn clean package

    # Step 5: Deploy the WAR file to Nexus Repository
    - name: Deploy to Nexus
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: |
        mvn deploy -DskipTests=true \
        -Dnexus.user=${{ secrets.NEXUS_USERNAME }} \
        -Dnexus.password=${{ secrets.NEXUS_PASSWORD }} \
        -Dnexus.url=https://nexus.example.com/repository/maven-releases/
