name: Build and Deploy to Nexus

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: windows-2022 

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 20
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'  

      # Step 3: List the files in the directory (debugging)
      - name: List directory contents
        run: dir  

      # Step 4: Run Maven build (ensure the correct directory)
      - name: Build with Maven
        run: mvn clean package
        working-directory: F:\java_test\New-java-app

      # Step 5: Upload WAR file to Nexus
      - name: Upload WAR to Nexus
        run: mvn deploy
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_URL: ${{ secrets.NEXUS_URL }}
